name: my-sso

services:
  postgres:
    image: postgres
    container_name: my-sso-postgres
    environment:
      POSTGRES_DB: my-sso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - my-sso_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  my-sso_postgres_data: